Modernize a bit
patrykandpatryk/vico pull request #110
Opened 2022-07-24 10:23 UTC by Goooler

2022-07-24 10:23 UTC, Goooler commented on .github/workflows/build_debug_apk.yml
> +      - uses: gradle/gradle-build-action@v2
https://github.com/gradle/gradle-build-action

2022-07-24 10:33 UTC, Goooler commented on .github/workflows/build_debug_apk.yml
> +
If we need to limit CI run on PRs and pushes on master only?

2022-07-24 17:44 UTC, Gowsky commented
Thanks for the PR! Would you mind explaining the benefits of changes in gradle-wrapper files?

2022-07-25 01:29 UTC, Goooler commented
> Thanks for the PR! Would you mind explaining the benefits of changes in gradle-wrapper files?

Auto generated by `./gradlew wrapper --gradle-version=7.5`, see https://docs.gradle.org/7.5/release-notes.html

2022-07-25 08:11 UTC, patrykmichalik commented
Hello, and thanks for the PR! Because we donʼt push directly to `master`, Iʼve changed the base branch to `development`, but that has caused a couple of conflicts. Would you be able to rebase your branch onto `patrykandpatryk:development`?

2022-07-25 08:29 UTC, Goooler commented
Done. And you can use squash commit on this PR.

2022-07-26 17:33 UTC, patrykmichalik commented on .github/workflows/build_debug_apk.yml
> +
We generally prefer having this workflow run for all pushes. This way, potential issues can be identified earlier.

2022-07-26 17:39 UTC, patrykmichalik requested changes

2022-07-26 17:41 UTC, patrykmichalik commented on .github/workflows/build_debug_apk.yml
> +
We generally prefer having this workflow run for all pushes. This way, potential issues can be identified earlier. If there are no branches specified under `push`, does the addition of `pull_request` change anything? 🤔

2022-07-26 23:59 UTC, Goooler commented on .github/workflows/build_debug_apk.yml
> +
Will run twice for each commit in PRs.

2022-07-28 14:31 UTC, patrykmichalik requested changes

2022-07-28 14:31 UTC, patrykmichalik commented on .github/workflows/build_debug_apk.yml
> +
Got it. Given that we’d rather have this workflow run for all pushes, I’d suggest reverting this change, as having CI run twice for the same commit is redundant.

2022-07-28 14:31 UTC, patrykmichalik commented on .gitignore
> +.idea
This would exclude the entire `.idea` directory, but some files included in this directory should be added to version control. Consequently, I’d suggest reverting this change.

2022-07-28 14:32 UTC, patrykmichalik commented on .github/workflows/build_debug_apk.yml
> +
Got it. Given that we’d like this workflow to run for all pushes, I’d suggest reverting this change, as having CI run twice for the same commit is redundant.

2022-07-28 14:33 UTC, patrykmichalik commented on .github/workflows/build_debug_apk.yml
> +      - uses: gradle/gradle-build-action@v2
Looks good!

2022-07-28 14:41 UTC, Goooler commented on .gitignore
> +.idea
Nothing special should be added, if needed, we can add it forcely?

2022-07-28 14:42 UTC, Goooler commented on .github/workflows/build_debug_apk.yml
> +
But no CI actions running for external PRs.

2022-07-28 15:05 UTC, patrykmichalik commented on .github/workflows/build_debug_apk.yml
> +
Ah, got it. Please disregard my suggestion, then. Let’s keep your edits.

2022-07-28 17:26 UTC, Gowsky commented on .gitignore
> +.idea
Yup, please revert this change and we can get this merged.

2022-07-29 01:39 UTC, Goooler commented on .gitignore
> +.idea
23b0fa5681adcce9bd47d24442898b63af62f31f

2022-07-29 08:21 UTC, patrykmichalik requested changes

2022-07-29 08:21 UTC, patrykmichalik commented on .gitignore
>  local.properties
I’d suggest deleting this line, as it’s a duplicate of line 3.
```suggestion
```

2022-07-29 08:47 UTC, merged

2022-07-29 08:47 UTC, patrykmichalik commented
Cheers, @Goooler!

2022-07-29 08:48 UTC, patrykmichalik commented on .gitignore
> +.idea
Thanks!