[Sample] Add ability to click on arrows within SwipeHint
patrykandpatryk/vico pull request #129
Opened 2022-09-10 01:13 UTC by evowizz

This PR adds the ability to click on arrows within the `SwipeHint` (located below the charts in the sample. While this isn't the most useful PR of all, it fixes a small confusion I've had multiple times most of the time I've tried the sample app.

The ability to swipe between pages remains available and the ability to click the arrows does not break it.

2022-09-11 10:57 UTC, patrykmichalik requested changes
Thanks for the PR! Here are some suggestions.

2022-09-11 10:57 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/ui/ChartPager.kt
> +                    pageCount = itemCount
It seems that a trailing comma is missing here.

```suggestion
                    pageCount = itemCount,
```

2022-09-11 10:57 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/ui/ChartPager.kt
> +                ) { direction: Int ->
For consistency with the rest of the source code, I’d suggest removing the type annotation here.

```suggestion
                ) { direction ->
```

2022-09-11 10:57 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/ui/ChartPager.kt
> +                    scope.launch { state.animateTo(newState) }
I think it would be preferable for `animateTo` not to be called at all when `state.currentValue + direction` is outside of the `0 until itemCount` range. This would reduce the number of operations.

```suggestion
                    scope.launch {
                        (state.currentValue + direction)
                            .takeIf { it in 0 until itemCount }
                            ?.let { state.animateTo(it) }
                    }
```

2022-09-11 11:10 UTC, evowizz commented on sample/src/main/java/com/patrykandpatryk/vico/sample/ui/ChartPager.kt
> +                    pageCount = itemCount
Oh, this isn't required by Kotlin. Besides, all parameters are already provided.

2022-09-11 11:21 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/ui/ChartPager.kt
> +                    pageCount = itemCount
While trailing commas are optional, the Kotlin style guide recommends that they be used—please see [here](https://kotlinlang.org/docs/coding-conventions.html#trailing-commas).

2022-09-11 11:40 UTC, evowizz commented on sample/src/main/java/com/patrykandpatryk/vico/sample/ui/ChartPager.kt
> +                    pageCount = itemCount
Fair enough 👍 You may want to add a code style to the project.

2022-09-11 16:46 UTC, patrykmichalik requested changes
Thanks! One last suggestion.

2022-09-11 16:46 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/ui/ChartPager.kt
> +                    val newState = (state.currentValue + direction)
These parentheses seem to be unnecessary.

```suggestion
                    val newState = state.currentValue + direction
```

2022-09-11 16:49 UTC, patrykmichalik approved these changes

2022-09-11 16:51 UTC, merged

2022-09-11 16:52 UTC, patrykmichalik commented
Thanks, @evowizz!

2022-09-12 09:26 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/ui/ChartPager.kt
> +                    pageCount = itemCount
It looks like `ALLOW_TRAILING_COMMA` is set to `true` in the project’s code style (see [here](https://github.com/patrykandpatryk/vico/blob/development/.idea/codeStyles/Project.xml#L15)). I’ve just added two rules connected to trailing commas to the `.editorconfig` file (see [here](https://github.com/patrykandpatryk/vico/blob/development/.editorconfig#L11-L13)).