Support multiple chart lines in `LineChart`
patrykandpatryk/vico pull request #74
Opened 2022-05-02 17:19 UTC by Gowsky

2022-05-02 17:27 UTC, Gowsky commented
![image](https://user-images.githubusercontent.com/14221573/166295240-64efb7dd-5877-413b-8c19-d193fa3f5943.png)

2022-05-03 19:09 UTC, patrykmichalik requested changes

2022-05-03 19:09 UTC, patrykmichalik commented on vico/view/src/main/java/com/patrykandpatryk/vico/view/chart/line/LineChartExtensions.kt
> + * The [styleResId] must define the style of at least one of [R.attr.line1spec], [R.attr.line2spec], [R.attr.line3spec].
```suggestion
 * The [styleResId] must define the style of at least one of the following: [R.attr.line1spec], [R.attr.line2spec], and [R.attr.line3spec].
```

2022-05-03 19:09 UTC, patrykmichalik commented on vico/view/src/main/java/com/patrykandpatryk/vico/view/chart/line/LineChartExtensions.kt
> + * Creates a [LineChart] using provided [List] of [themeAttrRes] and [styleResId].
```suggestion
 * Creates a [LineChart] using the provided [List] of theme attribute resource identifiers and the given [styleResId].
```

2022-05-03 19:09 UTC, patrykmichalik commented on vico/view/src/main/java/com/patrykandpatryk/vico/view/chart/line/LineChartExtensions.kt
> + * @param context a Context used to retrieve the style information.
```suggestion
 * @param context the context used to retrieve the style information.
```

2022-05-03 19:09 UTC, patrykmichalik commented on vico/view/src/main/java/com/patrykandpatryk/vico/view/chart/line/LineChartExtensions.kt
> + * @param themeAttrRes a [List] of theme attributes resource identifiers used to retrieve [LineChart.LineSpec] styles.
```suggestion
 * @param themeAttrRes a [List] of theme attribute resource identifiers used to retrieve [LineChart.LineSpec] styles.
```

2022-05-03 19:09 UTC, patrykmichalik commented on vico/view/src/main/java/com/patrykandpatryk/vico/view/chart/line/LineChartExtensions.kt
> + * The [styleResId] must define the style of at least one of [R.attr.line1spec], [R.attr.line2spec], [R.attr.line3spec].
```suggestion
 * The [styleResId] must define the style of at least one of the following: [R.attr.line1spec], [R.attr.line2spec], and [R.attr.line3spec].
```

2022-05-03 19:09 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/compose/component/ComposedChart.kt
> +            )
```suggestion
            ),
```

2022-05-03 19:09 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/compose/component/ComposedChart.kt
> +        )
```suggestion
        ),
```

2022-05-03 19:09 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/compose/component/ComposedChart.kt
> +
```suggestion
```

2022-05-03 19:09 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/compose/component/LineChartWithLabelsInside.kt
> +                lineSpec(lineBackgroundShader = null)
```suggestion
                lineSpec(lineBackgroundShader = null),
```

2022-05-03 19:09 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/compose/component/LineChartWithLabelsInside.kt
> +            )
```suggestion
            ),
```

2022-05-03 19:09 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/compose/preview/LineChartPreviews.kt
> +                        )
```suggestion
                        ),
```

2022-05-03 19:09 UTC, patrykmichalik commented on sample/src/main/java/com/patrykandpatryk/vico/sample/fragment/ViewShowcaseFragment.kt
> +                    )
```suggestion
                    ),
```

2022-05-03 19:09 UTC, patrykmichalik commented on vico/view/src/main/java/com/patrykandpatryk/vico/view/chart/line/LineChartExtensions.kt
> + * @param context a Context used to retrieve the style information.
```suggestion
 * @param context the context used to retrieve the style information.
```

2022-05-03 19:09 UTC, patrykmichalik commented on vico/view/src/main/java/com/patrykandpatryk/vico/view/chart/line/LineChartExtensions.kt
> + * @param themeAttrRes a theme attributes resource identifier used to retrieve [LineChart.LineSpec]’s style.
```suggestion
 * @param themeAttrRes a theme attributes resource identifier used to retrieve the [LineChart.LineSpec]’s style.
```

2022-05-04 18:59 UTC, patrykmichalik approved these changes
Nice work! 🎉

2022-05-04 19:00 UTC, merged